version: "3.8"

services:
  paperpod:
    build: .
    container_name: paperpod
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - UPLOAD_FOLDER=uploads
      - MAX_CONTENT_LENGTH=16777216
    restart: unless-stopped
